import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import '../globals.css'
import { Header } from '@root/components/organisms/header/header'
import { Footer } from '@root/components/organisms/footer/footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface LocaleLayoutProps {
    children: React.ReactNode
    params: {
        locale: string
    }
}

export default function LocaleLayout({ children, params: { locale } }: LocaleLayoutProps) {
    return (
        <html lang={locale}>
            <body className={`${montserrat.className} text-lg`}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    )
}
